### ISSUE TITLE
issue with runing the project

### ISSUE THREAD

**Issue by shay86** [DeepLearning4BioSeqText/Paper16-AAAI-MUST-CNN#1]
hi,
I am trying to run this project, but got this error any help 
thanks in advance 
![screenshot from 2017-05-28 11-11-26](https://cloud.githubusercontent.com/assets/27968351/26530280/ddc3082e-4397-11e7-9689-a40237c0b5e2.png)

**Comment by ebetica** [comment]
https://github.com/torch/distro/issues/163

Just do `unpack = table.unpack` at the beginning of the code. Lua 5.2 no longer has unpack.

**Comment by shay86** [comment]
hi,
thank you for answering me so fast, but i got this new issue and i am new to torch i dont know how to fix it.
thanks for your help
![new](https://cloud.githubusercontent.com/assets/27968351/26531986/51e9c116-43bb-11e7-9f02-08d46a277063.png)
