### ISSUE TITLE
issue with project 

### ISSUE THREAD

**Issue by shay86** [DeepLearning4BioSeqText/Paper16-AAAI-MUST-CNN#2]
hi,
I got this new issue and I am new to torch i don't know how to fix it. i Google it and it seem to be some common version issue. Do any on know how to solve this problem. Knowing I am using the project data without any change. thanks for help in advance.
![new](https://cloud.githubusercontent.com/assets/27968351/26533210/4f45a7ca-43db-11e7-9210-ee7453f85c3c.png)

**Comment by ebetica** [comment]
I think the truncation behavior of ClassNLLCriterion changed. What you might be able to do is to reshape the inputs to be the same size as the targets in https://github.com/DeepLearning4BioSeqText/Paper16-AAAI-MUST-CNN/blob/master/Trainer.lua#L70, and do the opposite at https://github.com/DeepLearning4BioSeqText/Paper16-AAAI-MUST-CNN/blob/master/Trainer.lua#L92.

Sorry we're not really keeping this up to date, I might do a pytorch version of this later. You can also try installing an older version of torch, from December 2015 or so.

**Comment by shay86** [comment]
thank you for answering me
can you send me which version of Torch ,Lua and Cuda you installed and used .So I try to install it because i think the error not from the code it self but because it is not compatible with the new versions

**Comment by ebetica** [comment]
I do not have a version installed anywhere anymore. I'm not completely sure if this version works (just look in torch7/distro and pick an old enough commit) but it should. I believe we were on CUDA 5, though CUDA 6 might also work.

```
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; git checkout b3c2671b0fb7b19a5e3a92e1f5e494a8c3f2fcc9
bash install-deps;
./install.sh
```
